name: better_require_trailing_commas
description: A lint rule that enforces trailing commas behaves like ESLint’s comma-dangle with the always-multiline option.
version: 2.3.0
repository: https://github.com/chika3742/better_require_trailing_commas

environment:
  sdk: ^3.10.0

dependencies:
  meta: ^1.17.0
  analyzer: ^9.0.0
  analyzer_plugin: ^0.13.11
  analysis_server_plugin: ^0.3.4

dev_dependencies:
  analyzer_testing: ^0.1.7
  lints: ^6.0.0
  test_reflective_loader: ^0.4.0
